/**
 * File generated by Magnet rest2mobile 1.1 - Jul 30, 2015 2:10:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ashokslsk.movielist.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.ashokslsk.movielist.controller.api.RTMovie;
import com.ashokslsk.movielist.controller.api.RTMovieFactory;
import com.ashokslsk.movielist.model.beans.*;
import java.util.List;

/**
* This is generated stub to test {@link RTMovie}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class RTMovieTest extends InstrumentationTestCase {
  private RTMovie rTMovie;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    RTMovieFactory controllerFactory = new RTMovieFactory(magnetClient);
    rTMovie = controllerFactory.obtainInstance();

    assertNotNull(rTMovie);
  }

  /**
    * Generated unit test for {@link RTMovie#getMovies}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testGetMovies() throws SchemaException, ExecutionException, InterruptedException {
    Call<List<MoviesResult>> callObject = rTMovie.getMovies(null);
    assertNotNull(callObject);

    List<MoviesResult> result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
