/**
 * File generated by Magnet rest2mobile 1.1 - Jul 30, 2015 2:10:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ashokslsk.movielist.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.ashokslsk.movielist.model.beans.*;
import java.util.List;

public class RTMovieFactory extends ControllerFactory<RTMovie> {
  public RTMovieFactory(MagnetMobileClient magnetClient) {
    super(RTMovie.class, RTMovieSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller RTMovie
  public static class RTMovieSchemaFactory extends AbstractControllerSchemaFactory {
    private static RTMovieSchemaFactory __instance;

    public static synchronized RTMovieSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new RTMovieSchemaFactory();
      }

      return __instance;
    }

    private RTMovieSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getMovies
      JMethod method1 = addMethod("getMovies",
        "json/movies.json",
        "GET",
        List.class,
        MoviesResult.class,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://api.androidhive.info");
    }

  }

}
