/**
 * File generated by Magnet rest2mobile 1.1 - Jul 30, 2015 2:10:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.ashokslsk.movielist.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.ashokslsk.movielist.model.beans.*;
import java.util.List;

public interface RTMovie {

  /**
   * Generated from URL GET http://api.androidhive.info/json/movies.json
   * GET json/movies.json
   * @param listener
   * @return List<MoviesResult>
   */
  Call<List<MoviesResult>> getMovies(StateChangedListener listener);
}
